### Find by number
GET http://localhost:8080/cars/find?number=XWBSA695ERA070217


### Find by number
GET http://localhost:8080/cars/find-for-add?number=XWBSA695ERA070219&latitude=40.659772&longitude=72.228832


